#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Set background image
feh --randomize --bg-fill ~/.wallpaper/*.jpg

# Remap capslock to escape
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42=Escape'
